/*

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.


Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.

*/

public class Solution {
    public char FindTheDifference(string s, string t) {
        int xor = 0;
        foreach(char c in s){
            xor = xor ^ (int)c;
        }
        foreach(char c in t){
            xor = xor ^ (int)c;
        }
        return (char)xor;
    }
}

/*
	TC = O(s.Length + t.Length) = O(1000+1001) = O(2001) = O(1)
	SC = O(1)
*/